"use client";

import {
  createContext,
  type ReactNode,
  useContext,
  useEffect,
  useMemo,
  useSyncExternalStore,
} from "react";

export type Language = "en" | "ja" | "zh";

const messages = {
  en: {
    "brand.tagline": "family learning",
    "nav.home": "Home",
    "nav.create": "Create",
    "nav.history": "History",
    "nav.library": "Library",
    "nav.family": "Family",
    "nav.work": "Work",
    "nav.review": "Review",
    "navigation.parent": "Parent navigation",
    "navigation.child": "Child navigation",
    "navigation.mobile": "{role} mobile navigation",
    "identity.parent": "Parent",
    "role.parent": "Parent mode",
    "role.child": "Child mode",
    "action.exitChild": "Exit child mode",
    "language.label": "Language",
    "parentDashboard.eyebrow": "Parent workspace",
    "parentDashboard.title": "Set up your family workspace",
    "parentDashboard.description":
      "Add your family and children before creating their first practice set.",
    "parentDashboard.firstStep": "First step",
    "parentDashboard.familyAction": "Create or join a family",
    "parentDashboard.familyDetails":
      "Family setup keeps each child's assignments, photos, results, and review schedule separate.",
    "parentDashboard.openFamilySetup": "Open family setup",
    "parentDashboard.private": "Private by default",
    "parentDashboard.accountReady": "Your account is ready",
    "parentDashboard.accountReadyDetails":
      "Nothing from the sample family is attached to your account. Your workspace starts empty and only shows the people you add or join.",
    "parentDashboard.continueFamilySetup": "Continue to family setup",
    "parentDashboard.activeFamilyDescription":
      "{count} children are ready for learning in this family.",
    "parentDashboard.learningToday": "Learning today",
    "parentDashboard.noChildren": "Add a child before creating their first practice.",
    "parentDashboard.quickActions": "Family quick actions",
    "parentDashboard.workspaceUnavailable": "We could not load your family workspace",
    "parentDashboard.workspaceUnavailableDetails":
      "Your account is still signed in. Please try loading your family again.",
    "parentDashboard.tryAgain": "Try again",
    "family.eyebrow": "Family workspace",
    "family.createTitle": "Create your family",
    "family.loadingTitle": "Loading your workspace…",
    "family.description":
      "Parents share one family. Each member keeps an independent language preference.",
    "family.switcherLabel": "Family switcher",
    "family.currentLabel": "Current family",
    "family.choose": "Choose a family",
    "family.newNameLabel": "New family name",
    "family.newNamePlaceholder": "New family name",
    "family.add": "Add family",
    "family.invitation":
      "A family invitation for {email} expires {date}.",
    "family.accept": "Accept",
    "family.children": "Children",
    "family.profilesPin": "Profiles and PIN",
    "family.managementPin": "Parent management PIN",
    "family.sixDigits": "6 digits",
    "family.managementUnlocked": "Management unlocked for 10 minutes",
    "family.unlockPin": "Unlock PIN controls",
    "family.setManagementPin": "Set management PIN",
    "family.managementNote":
      "A short management unlock is required before a child PIN can be changed.",
    "family.uiLanguage": "{language} UI",
    "family.languageFor": "UI language for {name}",
    "family.createPractice": "Create practice",
    "family.childSignIn": "Child sign in",
    "family.newPinFor": "New PIN for {name}",
    "family.pinPlaceholder": "6-digit PIN",
    "family.savePin": "Save PIN",
    "family.managePin": "Manage PIN",
    "family.childName": "Child name",
    "family.grade": "Grade",
    "family.sixDigitPin": "Six-digit PIN",
    "family.childUiLanguage": "Child UI language",
    "family.addChild": "Add child",
    "language.option.zh": "Chinese",
    "language.option.ja": "Japanese",
    "language.option.en": "English",
    "childLogin.eyebrow": "Child sign in",
    "childLogin.title": "Enter your six-digit PIN",
    "childLogin.help": "A parent can reset this PIN from Family settings.",
    "childLogin.digitsEntered": "{count} of 6 digits entered",
    "childLogin.deleteDigit": "Delete last digit",
    "childLogin.opening": "Opening…",
    "childLogin.openWork": "Open my work",
    "childLogin.error": "That PIN did not work. Please try again.",
    "childLogin.expired":
      "Your child session expired. Enter the PIN again to continue.",
    "childLogin.returnParent": "Return to parent mode",
    "childHome.today": "Today",
    "childHome.title": "Ready for a small win?",
    "childHome.assignmentOne": "{count} assignment",
    "childHome.assignmentMany": "{count} assignments",
    "childHome.reviewOne": "{count} review question",
    "childHome.reviewMany": "{count} review questions",
    "childHome.summary": "{assignments} and {reviews}.",
    "childHome.loadingSummary": "Loading today’s learning plan…",
    "childHome.start": "Start",
    "childHome.status.inProgress": "In progress",
    "childHome.status.submitted": "Submitted",
    "childHome.status.grading": "Being checked",
    "childHome.status.resultsReady": "Results ready",
    "childHome.status.completed": "Completed",
    "childHome.examMode": "Exam mode",
    "childHome.practiceMode": "Practice mode",
    "childHome.questions": "{count} questions",
    "childHome.minutes": "{count} min",
    "childHome.noTimer": "no timer",
    "childHome.viewStatus": "View status",
    "childHome.openWork": "Open work",
    "childHome.allClear": "All clear",
    "childHome.noAssigned": "No assigned work is waiting.",
    "childHome.parentCanAssign":
      "A parent can assign the next practice from the family workspace.",
    "childHome.todayReview": "Today's review",
    "childHome.shortQuestions": "{count} short questions",
    "childHome.reviewNote":
      "You can skip today. Missed work will be rescheduled gently.",
    "childHome.startReview": "Start review",
    "childHome.viewReview": "View review",
    "childHome.localDemo":
      "Showing the local demo until a child signs in with a real profile.",
    "worksheet.assignedPractice": "Assigned practice",
    "worksheet.multipleChoice": "Choose every correct answer",
    "worksheet.buildSentence": "Build the sentence",
    "worksheet.chooseWords": "Choose words below…",
    "worksheet.reset": "Reset",
    "worksheet.playSlow": "Play at 0.85×",
    "worksheet.playsUsed": "{count} / {limit} plays used",
    "worksheet.singleChoice": "Choose one answer",
    "worksheet.photoInput": "Take a photo or choose images",
    "worksheet.addMoreImages": "Add more answer images",
    "worksheet.photoHelp":
      "Upload one question at a time. Images stay in shooting order.",
    "worksheet.uploadedImages": "Uploaded answer images",
    "worksheet.yourAnswer": "Your answer",
    "worksheet.typeHere": "Type here…",
    "worksheet.handwritingAlternative":
      "You can also switch this question to handwriting from the menu.",
    "worksheet.questionMeta": "Question {number} · {points}",
    "worksheet.pointOne": "{count} point",
    "worksheet.pointMany": "{count} points",
    "worksheet.todayPractice": "Today's practice",
    "worksheet.practiceMode": "Practice mode",
    "worksheet.saving": "Saving…",
    "worksheet.saved": "Saved",
    "worksheet.savedDevice": "Saved on this device",
    "worksheet.autoSave": "Saves automatically",
    "worksheet.layout": "Worksheet layout",
    "worksheet.focusMode": "Focus mode",
    "worksheet.sheetMode": "Worksheet mode",
    "worksheet.answered": "answered",
    "worksheet.goToQuestion": "Go to question {number}",
    "worksheet.examTimer": "Exam timer · auto-submit at zero",
    "worksheet.noTimer": "No timer · Take your time",
    "worksheet.previous": "Previous",
    "worksheet.next": "Next question",
    "worksheet.submit": "Submit all answers",
    "worksheet.submitQuestion": "Submit this answer for grading",
    "worksheet.submitQuestionAgain": "Submit again for review",
    "worksheet.questionSubmitted": "This answer has been submitted",
    "worksheet.regradeAnswer": "Keep answer and regrade",
    "worksheet.regradingAnswer": "Regrading this answer…",
    "worksheet.redoQuestion": "Clear and redo this question",
    "worksheet.preparingRedo": "Preparing a blank answer…",
    "worksheet.confirmQuestionTitle": "Submit only this answer?",
    "worksheet.confirmQuestionBody":
      "Only question {number} will be submitted. You can continue the other questions, but this answer cannot be changed.",
    "worksheet.confirmQuestionAction": "Confirm single-answer submission",
    "worksheet.confirmAllTitle": "Submit the entire practice?",
    "worksheet.confirmAllBody":
      "{count} unanswered questions will be marked incorrect. No answer can be changed after the entire practice is submitted.",
    "worksheet.confirmAllAction": "Confirm full submission",
    "worksheet.cancel": "Cancel",
    "worksheet.grading": "Grading this answer…",
    "worksheet.result.correct": "Correct.",
    "worksheet.result.incorrect": "Review this answer.",
    "worksheet.result.uncertain": "The grader is not certain.",
    "worksheet.result.needsParentReview": "Waiting for parent review.",
    "worksheet.result.pending": "Waiting for a result.",
    "worksheet.result.action.correct": "Continue to the next question.",
    "worksheet.result.action.incorrect":
      "Review the feedback and try this question again.",
    "worksheet.result.action.review": "Ask a parent to confirm this answer.",
    "worksheet.loading": "Loading",
    "worksheet.loadingTitle": "Opening your assigned practice…",
    "worksheet.loadingBody": "This should only take a moment.",
    "worksheet.unavailable": "Unavailable",
    "worksheet.signInRequired": "Sign in as a child to open this practice.",
    "worksheet.loadError": "We could not open this practice.",
    "worksheet.tryAgain": "Return home, then try opening the practice again.",
    "handwriting.tools": "Handwriting tools",
    "handwriting.thinPen": "Thin pen",
    "handwriting.thickPen": "Thick pen",
    "handwriting.eraser": "Eraser",
    "handwriting.undo": "Undo",
    "handwriting.redo": "Redo",
    "handwriting.clear": "Clear handwriting",
    "handwriting.clearConfirm": "Clear all handwriting?",
    "handwriting.keep": "Keep handwriting",
    "handwriting.clearNow": "Clear now",
    "handwriting.expandRight": "Add space to the right",
    "handwriting.expandDown": "Add space below",
    "handwriting.area": "Handwriting answer area",
    "handwriting.help":
      "Use a finger or stylus. Add space to the right or below when needed. Your work saves as you write.",
    "submitted.eyebrow": "All handed in",
    "submitted.title": "Your work is being checked",
    "submitted.description":
      "You finished the whole set. Results appear together when every answer is ready.",
    "submitted.duration": "Usually a few minutes",
    "submitted.viewResults": "View results",
    "submitted.preparing": "Preparing results…",
    "results.preparingCorrections": "Preparing corrections…",
    "results.correctAnswers": "Correct these answers",
    "results.ready": "Results ready",
    "results.checking": "Checking your work",
    "results.goodWork": "Good work, {name}",
    "results.almostReady": "Almost ready",
    "results.unavailable": "Results unavailable",
    "results.unavailableTitle": "No results to show",
    "results.unavailableBody":
      "Open a submitted assignment from History to see its results.",
    "results.correctionOne":
      "{count} answer is ready for one more try or a parent check.",
    "results.correctionMany":
      "{count} answers are ready for one more try or a parent check.",
    "results.fullResult":
      "The full result appears only after every answer is checked.",
    "results.points": "points",
    "results.question": "Question {number}",
    "results.correct": "Correct",
    "results.tryAgain": "Try once more",
    "results.parentCheck": "Waiting for a parent",
    "results.demoAction": "Check the subject and the verb ending.",
    "results.openError":
      "Corrections could not be opened. Please try again.",
    "parentResults.eyebrow": "{name} · {title}",
    "parentResults.title": "Review answers",
    "parentResults.description":
      "Only handwriting, photos, and answers that need your decision appear here.",
    "parentResults.loading": "Loading answers…",
    "parentResults.error":
      "These results could not be loaded. Return to History and try again.",
    "parentResults.missingAttempt":
      "Open this page from a completed item in History.",
    "parentResults.processing":
      "The grading results are being finalized. This page will update automatically.",
    "parentResults.allReviewed": "All answers have been reviewed.",
    "parentResults.question": "Question {number} · {type}",
    "parentResults.handwriting": "Handwriting",
    "parentResults.photo": "Photo answer",
    "parentResults.answer": "Child's answer",
    "parentResults.handwritingPreview": "Child's handwritten answer",
    "parentResults.photoList": "Uploaded answer photos",
    "parentResults.parentNeeded":
      "The system did not score this visual answer. Please decide from the child's work.",
    "parentResults.markCorrect": "Mark correct",
    "parentResults.markIncorrect": "Needs correction",
    "parentResults.saving": "Saving…",
    "parentResults.savedCorrect":
      "A parent marked this answer correct.",
    "parentResults.savedIncorrect":
      "A parent marked this answer incorrect.",
    "parentResults.decisionError":
      "The decision could not be saved. Please try again.",
    "parentResults.wholeSet": "Whole set",
    "parentResults.score": "{awarded} / {available} points",
    "parentResults.correct": "Correct",
    "parentResults.correction": "Correction",
    "parentResults.pending": "Parent review",
    "parentResults.releaseNote":
      "Automatic results and parent decisions are combined into the final score.",
    "review.today": "Today's review",
    "review.quickOne": "{count} quick question",
    "review.quickMany": "{count} quick questions",
    "review.description":
      "A short mix at the right level, with no timer.",
    "review.loading": "Loading today's review…",
    "review.none": "Nothing is due today.",
    "review.backHome": "Back home",
    "review.level.reinforcement": "Reinforcement",
    "review.level.standard": "Standard",
    "review.level.challenge": "Challenge",
    "review.next": "Next review: {date}",
    "review.gotIt": "I got it",
    "review.anotherTry": "I need another try",
    "review.skip": "Skip for today",
    "history.eyebrow": "Your work",
    "history.title": "History",
    "history.description": "Finished sets, scores, and corrections.",
    "history.loading": "Loading learning history…",
    "history.empty": "No learning history yet.",
    "history.error": "History could not be loaded. Please sign in again.",
    "history.assigned": "Assigned",
    "history.correctionOne": "{count} correction",
    "history.correctionMany": "{count} corrections",
    "history.status.draft": "Draft",
    "history.status.confirmed": "Confirmed",
    "history.status.assigned": "Assigned",
    "history.status.inProgress": "In progress",
    "history.status.submitted": "Submitted",
    "history.status.grading": "Being checked",
    "history.status.resultsReady": "Results ready",
    "history.status.correcting": "Correcting",
    "history.status.completed": "Completed",
    "history.status.other": "Updated",
    "history.openResults": "Open results for {title}",
    "history.results": "Results",
    "parentHistory.eyebrow": "Family learning record",
    "parentHistory.title": "Learning history",
    "parentHistory.description":
      "Completed, grading, and archived work for every child in this family.",
    "parentHistory.filters": "Learning history filters",
    "parentHistory.allChildren": "All children",
    "parentHistory.loading": "Loading family history…",
    "parentHistory.missing": "Select a family to view its history.",
    "parentHistory.error": "Family history could not be loaded.",
    "parentHistory.empty": "No family learning history yet.",
    "parentHistory.points": "{awarded} / {available} points",
    "parentHistory.withdraw": "Withdraw assignment",
    "parentHistory.stop": "Stop assignment",
    "parentHistory.status.withdrawn": "Withdrawn",
    "parentHistory.status.stopped": "Stopped",
    "parentHistory.actionError":
      "The assignment status could not be updated. Please retry.",
    "completedPaper.eyebrow": "Completed worksheet received",
    "completedPaper.mode": "Grade completed paper",
    "completedPaper.readingTitle": "Reading the paper",
    "completedPaper.reviewTitle": "Preparing the review draft",
    "completedPaper.description":
      "The original paper is private. Question boundaries and scoring must be confirmed before it becomes a learning record.",
    "completedPaper.analysisProcessing": "Analysis in progress",
    "completedPaper.analysisReady": "Analysis ready for review",
    "completedPaper.submitted": "Submitted for grading",
    "completedPaper.preparing": "Your paper is being prepared",
    "completedPaper.notAssigned": "Paper upload is safe and not yet assigned",
    "completedPaper.submittedDetails":
      "The paper is now an immutable learning record. Results appear when grading finishes.",
    "completedPaper.preparingDetails":
      "We are preparing a private review draft. This page will update automatically; no child task has been created.",
    "completedPaper.reviewDetails":
      "Confirm the reviewed question and answer regions. Only then will it create a submitted attempt and start grading.",
    "completedPaper.openResults": "Open grading results",
    "completedPaper.prepareLocal": "Prepare a local AI review JSON",
    "completedPaper.localDetails":
      "Attach the original pages to your local AI, copy this prompt, and save its JSON-only response. The prompt never asks for a storage path; this app adds the private paper reference itself.",
    "completedPaper.serverDraft":
      "A private AI draft is ready. Review every question and answer region before confirming.",
    "completedPaper.promptCopied": "Prompt copied",
    "completedPaper.copyPrompt": "Copy local AI prompt",
    "completedPaper.reviewJson": "Reviewed completed worksheet JSON",
    "completedPaper.chooseJson": "Choose reviewed paper JSON",
    "completedPaper.jsonHelp":
      "The app validates question order and answer regions before creating a learning record.",
    "completedPaper.reviewReady": "Review ready · questions: {questions} · answer regions: {regions}",
    "completedPaper.previewQuestions": "Preview confirmed questions",
    "completedPaper.questionWording": "Question wording",
    "completedPaper.questionWordingFor": "Question {position} wording",
    "completedPaper.removeQuestion": "Remove question {position}",
    "completedPaper.addHandwritingQuestion": "Add handwritten question",
    "completedPaper.referenceAnswer": "Reference answer (private)",
    "completedPaper.referenceAnswerFor": "Reference answer for question {position}",
    "completedPaper.acceptedAnswer": "Accepted answer",
    "completedPaper.acceptedAnswerFor": "Accepted answer for question {position}",
    "completedPaper.correctChoice": "Correct choice",
    "completedPaper.correctChoiceFor": "Correct choice for question {position}",
    "completedPaper.correctChoices": "Correct choices",
    "completedPaper.correctChoiceOptionFor": "Correct choice {choice} for question {position}",
    "completedPaper.correctWordOrder": "Correct word order (one token per line)",
    "completedPaper.correctWordOrderFor": "Correct word order for question {position}",
    "completedPaper.answerPages": "Answer page numbers",
    "completedPaper.answerPagesFor": "Answer page numbers for question {position}",
    "completedPaper.answerTranscription": "Answer transcription (private)",
    "completedPaper.answerTranscriptionFor": "Answer transcription for question {position}",
    "completedPaper.legibility": "Handwriting legibility",
    "completedPaper.legibilityFor": "Handwriting legibility for question {position}",
    "completedPaper.legibility.clear": "Clear",
    "completedPaper.legibility.uncertain": "Uncertain",
    "completedPaper.legibility.unreadable": "Unreadable",
    "completedPaper.useWholePage": "Use the whole page instead",
    "completedPaper.page": "Page {pages}",
    "completedPaper.confirm": "Confirm and start grading",
    "completedPaper.confirming": "Confirming…",
    "completedPaper.preparingReview": "Preparing private review",
    "completedPaper.error":
      "The reviewed JSON must match every confirmed question and answer region. Nothing was assigned; correct it and try again.",
    "completedPaper.composeTitle": "Upload a paper the child has already completed",
    "completedPaper.composeDescription":
      "Upload the original scan or photos. The handwriting stays private and is reviewed only after you confirm the draft.",
    "completedPaper.scans": "Completed worksheet scans",
    "completedPaper.documentLanguage": "Worksheet language",
    "completedPaper.documentLanguageHelp":
      "This is the language printed on the paper, not the child's interface language.",
    "completedPaper.answerKey": "Answer key (private, optional)",
    "completedPaper.chooseAnswerKey": "Choose answer key",
    "completedPaper.answerKeyHelp":
      "Only the parent and the grading service can use it. Children never receive it.",
    "completedPaper.referenceMaterial": "Original material or examples (private, optional)",
    "completedPaper.chooseReferenceMaterial": "Add original material or examples",
    "completedPaper.referenceMaterialHelp":
      "Use this privately to identify the learning goal and interpret the worksheet.",
    "completedPaper.choosePages": "Choose completed worksheet pages",
    "completedPaper.pagesHelp":
      "Upload several pages in their photographed order. Nothing is assigned or graded until you confirm the review draft.",
    "childExit.eyebrow": "Parent check",
    "childExit.title": "Enter your management PIN",
    "childExit.help":
      "Child answers stay open until a parent unlocks this shared device.",
    "childExit.digitsEntered": "{count} of 6 digits entered",
    "childExit.deleteDigit": "Delete last digit",
    "childExit.checking": "Checking…",
    "childExit.returnParent": "Return to parent mode",
    "childExit.error":
      "A signed-in parent and the correct management PIN are required.",
    "family.parents": "Parents",
    "family.inviteParent": "Invite another parent",
    "family.inviteNote":
      "A family can have up to four parents. Invitations expire after seven days. The MVP does not send external email.",
    "family.parentEmail": "Parent email",
    "family.createInvite": "Create invite",
    "family.inviteCreated":
      "Invite created for {email}. They can accept it after signing in with that verified email.",
    "family.saveError":
      "The change could not be saved. Please check the details and try again.",
    "family.accountSettings": "Open my sign-in and language settings",
  },
  ja: {
    "brand.tagline": "家族で学ぶ",
    "nav.home": "ホーム",
    "nav.create": "作成",
    "nav.history": "履歴",
    "nav.library": "問題集",
    "nav.family": "家族",
    "nav.work": "学習",
    "nav.review": "復習",
    "navigation.parent": "保護者ナビゲーション",
    "navigation.child": "子どもナビゲーション",
    "navigation.mobile": "{role}モバイルナビゲーション",
    "identity.parent": "保護者",
    "role.parent": "保護者モード",
    "role.child": "子どもモード",
    "action.exitChild": "子どもモードを終了",
    "language.label": "言語",
    "parentDashboard.eyebrow": "保護者ワークスペース",
    "parentDashboard.title": "家族の学習スペースを設定",
    "parentDashboard.description":
      "最初の練習を作る前に、家族とお子さまを登録してください。",
    "parentDashboard.firstStep": "最初のステップ",
    "parentDashboard.familyAction": "家族を作成または参加",
    "parentDashboard.familyDetails":
      "家族設定では、お子さまごとの課題、写真、結果、復習予定を分けて管理します。",
    "parentDashboard.openFamilySetup": "家族設定を開く",
    "parentDashboard.private": "初期設定では非公開",
    "parentDashboard.accountReady": "アカウントの準備ができました",
    "parentDashboard.accountReadyDetails":
      "サンプル家族の情報はアカウントに紐づいていません。学習スペースは空の状態から始まり、追加または参加したメンバーだけが表示されます。",
    "parentDashboard.continueFamilySetup": "家族設定へ進む",
    "parentDashboard.activeFamilyDescription":
      "この家族には学習の準備ができたお子さまが {count} 人います。",
    "parentDashboard.learningToday": "今日の学習",
    "parentDashboard.noChildren": "最初の練習を作る前に、お子さまを追加してください。",
    "parentDashboard.quickActions": "家族のクイック操作",
    "parentDashboard.workspaceUnavailable": "家族の学習スペースを読み込めませんでした",
    "parentDashboard.workspaceUnavailableDetails":
      "アカウントにはログインしたままです。もう一度家族を読み込んでください。",
    "parentDashboard.tryAgain": "もう一度試す",
    "family.eyebrow": "家族の学習スペース",
    "family.createTitle": "家族を作成",
    "family.loadingTitle": "学習スペースを読み込み中…",
    "family.description":
      "保護者は一つの家族を共有し、各メンバーは表示言語を個別に選べます。",
    "family.switcherLabel": "家族の切り替え",
    "family.currentLabel": "現在の家族",
    "family.choose": "家族を選択",
    "family.newNameLabel": "新しい家族名",
    "family.newNamePlaceholder": "新しい家族名",
    "family.add": "家族を追加",
    "family.invitation":
      "{email} 宛ての家族招待は {date} に期限切れになります。",
    "family.accept": "参加する",
    "family.children": "子ども",
    "family.profilesPin": "プロフィールと PIN",
    "family.managementPin": "保護者管理 PIN",
    "family.sixDigits": "6桁の数字",
    "family.managementUnlocked": "管理機能を10分間解除しました",
    "family.unlockPin": "PIN 管理を解除",
    "family.setManagementPin": "管理 PIN を設定",
    "family.managementNote":
      "お子さまの PIN を変更するには、一時的に管理機能を解除する必要があります。",
    "family.uiLanguage": "{language} 表示",
    "family.languageFor": "{name} の表示言語",
    "family.createPractice": "練習を作成",
    "family.childSignIn": "子どもとしてログイン",
    "family.newPinFor": "{name} の新しい PIN",
    "family.pinPlaceholder": "6桁の PIN",
    "family.savePin": "PIN を保存",
    "family.managePin": "PIN を管理",
    "family.childName": "子どもの名前",
    "family.grade": "学年",
    "family.sixDigitPin": "6桁の PIN",
    "family.childUiLanguage": "子どもの表示言語",
    "family.addChild": "子どもを追加",
    "language.option.zh": "中国語",
    "language.option.ja": "日本語",
    "language.option.en": "英語",
    "childLogin.eyebrow": "子どもログイン",
    "childLogin.title": "6桁の PIN を入力",
    "childLogin.help": "保護者は家族設定からこの PIN をリセットできます。",
    "childLogin.digitsEntered": "6桁中 {count} 桁を入力済み",
    "childLogin.deleteDigit": "最後の数字を削除",
    "childLogin.opening": "開いています…",
    "childLogin.openWork": "学習を開く",
    "childLogin.error": "PIN が正しくありません。もう一度お試しください。",
    "childLogin.expired":
      "子どもセッションの有効期限が切れました。PIN をもう一度入力してください。",
    "childLogin.returnParent": "保護者モードに戻る",
    "childHome.today": "今日",
    "childHome.title": "小さな一歩を始めよう",
    "childHome.assignmentOne": "課題 {count} 件",
    "childHome.assignmentMany": "課題 {count} 件",
    "childHome.reviewOne": "復習問題 {count} 問",
    "childHome.reviewMany": "復習問題 {count} 問",
    "childHome.summary": "{assignments}、{reviews}。",
    "childHome.loadingSummary": "今日の学習予定を読み込んでいます…",
    "childHome.start": "開始",
    "childHome.status.inProgress": "学習中",
    "childHome.status.submitted": "提出済み",
    "childHome.status.grading": "採点中",
    "childHome.status.resultsReady": "結果を確認できます",
    "childHome.status.completed": "完了",
    "childHome.examMode": "テストモード",
    "childHome.practiceMode": "練習モード",
    "childHome.questions": "{count} 問",
    "childHome.minutes": "{count} 分",
    "childHome.noTimer": "時間制限なし",
    "childHome.viewStatus": "状態を確認",
    "childHome.openWork": "学習を開く",
    "childHome.allClear": "すべて完了",
    "childHome.noAssigned": "待っている課題はありません。",
    "childHome.parentCanAssign":
      "次の練習は保護者が家族の学習スペースから割り当てられます。",
    "childHome.todayReview": "今日の復習",
    "childHome.shortQuestions": "短い問題 {count} 問",
    "childHome.reviewNote":
      "今日はスキップできます。できなかった復習は無理なく次回へ移動します。",
    "childHome.startReview": "復習を始める",
    "childHome.viewReview": "復習を見る",
    "childHome.localDemo":
      "実際の子どもプロフィールでログインするまで、端末内のデモを表示します。",
    "worksheet.assignedPractice": "割り当てられた練習",
    "worksheet.multipleChoice": "正しい答えをすべて選んでください",
    "worksheet.buildSentence": "文を組み立てる",
    "worksheet.chooseWords": "下の単語を選んでください…",
    "worksheet.reset": "やり直す",
    "worksheet.playSlow": "0.85倍で再生",
    "worksheet.playsUsed": "{limit} 回中 {count} 回再生",
    "worksheet.singleChoice": "答えを一つ選んでください",
    "worksheet.photoInput": "写真を撮る、または画像を選ぶ",
    "worksheet.addMoreImages": "解答画像を追加",
    "worksheet.photoHelp":
      "一問ずつアップロードしてください。画像は撮影順に保存されます。",
    "worksheet.uploadedImages": "アップロード済みの解答画像",
    "worksheet.yourAnswer": "あなたの答え",
    "worksheet.typeHere": "ここに入力…",
    "worksheet.handwritingAlternative":
      "メニューから手書き回答に切り替えることもできます。",
    "worksheet.questionMeta": "問題 {number} · {points}",
    "worksheet.pointOne": "{count} 点",
    "worksheet.pointMany": "{count} 点",
    "worksheet.todayPractice": "今日の練習",
    "worksheet.practiceMode": "練習モード",
    "worksheet.saving": "保存中…",
    "worksheet.saved": "保存済み",
    "worksheet.savedDevice": "この端末に保存済み",
    "worksheet.autoSave": "自動保存",
    "worksheet.layout": "問題の表示方法",
    "worksheet.focusMode": "一問表示",
    "worksheet.sheetMode": "一覧表示",
    "worksheet.answered": "回答済み",
    "worksheet.goToQuestion": "問題 {number} へ移動",
    "worksheet.examTimer": "テスト時間 · 0秒で自動提出",
    "worksheet.noTimer": "時間制限なし · ゆっくり取り組めます",
    "worksheet.previous": "前の問題",
    "worksheet.next": "次の問題",
    "worksheet.submit": "すべての答えを提出",
    "worksheet.submitQuestion": "この答えだけ採点に出す",
    "worksheet.submitQuestionAgain": "もう一度採点に出す",
    "worksheet.questionSubmitted": "この答えは提出済みです",
    "worksheet.regradeAnswer": "答えを残して再採点",
    "worksheet.regradingAnswer": "同じ答えを再採点中…",
    "worksheet.redoQuestion": "この問題を消してやり直す",
    "worksheet.preparingRedo": "空の解答を準備中…",
    "worksheet.confirmQuestionTitle": "この答えだけ提出しますか？",
    "worksheet.confirmQuestionBody":
      "問題 {number} だけを提出します。他の問題は続けられますが、この答えは変更できなくなります。",
    "worksheet.confirmQuestionAction": "1問だけ提出する",
    "worksheet.confirmAllTitle": "練習全体を提出しますか？",
    "worksheet.confirmAllBody":
      "未回答の {count} 問は不正解になります。全体を提出した後は、どの答えも変更できません。",
    "worksheet.confirmAllAction": "全体を提出する",
    "worksheet.cancel": "キャンセル",
    "worksheet.grading": "この答えを採点中…",
    "worksheet.result.correct": "正解です。",
    "worksheet.result.incorrect": "この答えを見直しましょう。",
    "worksheet.result.uncertain": "自動採点では判断できませんでした。",
    "worksheet.result.needsParentReview": "保護者の確認待ちです。",
    "worksheet.result.pending": "結果を待っています。",
    "worksheet.result.action.correct": "次の問題へ進んでください。",
    "worksheet.result.action.incorrect":
      "フィードバックを確認して、もう一度この問題に取り組んでください。",
    "worksheet.result.action.review":
      "保護者にこの答えを確認してもらってください。",
    "worksheet.loading": "読み込み中",
    "worksheet.loadingTitle": "割り当てられた練習を開いています…",
    "worksheet.loadingBody": "まもなく表示されます。",
    "worksheet.unavailable": "利用できません",
    "worksheet.signInRequired": "子どもとしてログインして練習を開いてください。",
    "worksheet.loadError": "練習を開けませんでした。",
    "worksheet.tryAgain": "ホームに戻り、もう一度練習を開いてください。",
    "handwriting.tools": "手書きツール",
    "handwriting.thinPen": "細いペン",
    "handwriting.thickPen": "太いペン",
    "handwriting.eraser": "消しゴム",
    "handwriting.undo": "元に戻す",
    "handwriting.redo": "やり直す",
    "handwriting.clear": "手書きをすべて消す",
    "handwriting.clearConfirm": "手書きをすべて消しますか？",
    "handwriting.keep": "手書きを残す",
    "handwriting.clearNow": "今すぐ消す",
    "handwriting.expandRight": "右に解答欄を追加",
    "handwriting.expandDown": "下に解答欄を追加",
    "handwriting.area": "手書き解答欄",
    "handwriting.help":
      "指またはスタイラスで書いてください。必要に応じて右や下に解答欄を追加できます。書くたびに保存されます。",
    "submitted.eyebrow": "提出完了",
    "submitted.title": "答えを採点しています",
    "submitted.description":
      "すべての問題を提出しました。全問の採点が終わると、結果をまとめて表示します。",
    "submitted.duration": "通常は数分です",
    "submitted.viewResults": "結果を見る",
    "submitted.preparing": "結果を準備中…",
    "results.preparingCorrections": "やり直しを準備中…",
    "results.correctAnswers": "この問題をやり直す",
    "results.ready": "結果を確認できます",
    "results.checking": "採点中",
    "results.goodWork": "よくできました、{name}",
    "results.almostReady": "もう少しです",
    "results.unavailable": "結果を表示できません",
    "results.unavailableTitle": "表示できる結果がありません",
    "results.unavailableBody":
      "学習履歴から提出済みの練習を開いてください。",
    "results.correctionOne":
      "{count} 問をもう一度解くか、保護者に確認してもらいます。",
    "results.correctionMany":
      "{count} 問をもう一度解くか、保護者に確認してもらいます。",
    "results.fullResult": "すべての採点が終わると結果をまとめて表示します。",
    "results.points": "点",
    "results.question": "問題 {number}",
    "results.correct": "正解",
    "results.tryAgain": "もう一度",
    "results.parentCheck": "保護者の確認待ち",
    "results.demoAction": "主語と動詞の語尾を確認しましょう。",
    "results.openError":
      "やり直しを開けませんでした。もう一度お試しください。",
    "parentResults.eyebrow": "{name} · {title}",
    "parentResults.title": "解答結果を確認",
    "parentResults.description":
      "手書き、写真、または保護者の判断が必要な解答だけを表示します。",
    "parentResults.loading": "解答を読み込み中…",
    "parentResults.error":
      "結果を読み込めませんでした。学習履歴からもう一度お試しください。",
    "parentResults.missingAttempt":
      "学習履歴の完了した課題からこの画面を開いてください。",
    "parentResults.processing":
      "採点結果をまとめています。この画面は自動的に更新されます。",
    "parentResults.allReviewed": "すべての解答を確認しました。",
    "parentResults.question": "問題 {number} · {type}",
    "parentResults.handwriting": "手書き",
    "parentResults.photo": "写真解答",
    "parentResults.answer": "お子さまの解答",
    "parentResults.handwritingPreview": "お子さまの手書き解答",
    "parentResults.photoList": "アップロードした解答写真",
    "parentResults.parentNeeded":
      "この画像の解答は自動採点していません。内容を見て判定してください。",
    "parentResults.markCorrect": "正解にする",
    "parentResults.markIncorrect": "やり直しにする",
    "parentResults.saving": "保存中…",
    "parentResults.savedCorrect": "保護者が正解と判定しました。",
    "parentResults.savedIncorrect": "保護者が不正解と判定しました。",
    "parentResults.decisionError":
      "判定を保存できませんでした。もう一度お試しください。",
    "parentResults.wholeSet": "全体",
    "parentResults.score": "{awarded} / {available} 点",
    "parentResults.correct": "正解",
    "parentResults.correction": "やり直し",
    "parentResults.pending": "保護者確認",
    "parentResults.releaseNote":
      "自動採点と保護者の判定を合わせて最終得点を計算します。",
    "review.today": "今日の復習",
    "review.quickOne": "すぐできる復習 {count} 問",
    "review.quickMany": "すぐできる復習 {count} 問",
    "review.description": "今の力に合った短い復習です。時間制限はありません。",
    "review.loading": "今日の復習を読み込み中…",
    "review.none": "今日の復習はありません。",
    "review.backHome": "ホームに戻る",
    "review.level.reinforcement": "基礎固め",
    "review.level.standard": "標準",
    "review.level.challenge": "チャレンジ",
    "review.next": "次の復習：{date}",
    "review.gotIt": "できた",
    "review.anotherTry": "もう一度練習する",
    "review.skip": "今日はスキップ",
    "history.eyebrow": "あなたの学習",
    "history.title": "学習履歴",
    "history.description": "完了した練習、得点、やり直しの記録です。",
    "history.loading": "学習履歴を読み込んでいます…",
    "history.empty": "学習履歴はまだありません。",
    "history.error":
      "学習履歴を読み込めませんでした。もう一度ログインしてください。",
    "history.assigned": "割り当て済み",
    "history.correctionOne": "やり直し {count} 問",
    "history.correctionMany": "やり直し {count} 問",
    "history.status.draft": "下書き",
    "history.status.confirmed": "確認済み",
    "history.status.assigned": "割り当て済み",
    "history.status.inProgress": "学習中",
    "history.status.submitted": "提出済み",
    "history.status.grading": "採点中",
    "history.status.resultsReady": "結果を確認できます",
    "history.status.correcting": "やり直し中",
    "history.status.completed": "完了",
    "history.status.other": "更新済み",
    "history.openResults": "{title} の結果を開く",
    "history.results": "結果",
    "parentHistory.eyebrow": "家族の学習記録",
    "parentHistory.title": "学習履歴",
    "parentHistory.description":
      "この家族の子ども全員の、完了・採点中・保存済みの練習を確認できます。",
    "parentHistory.filters": "学習履歴の絞り込み",
    "parentHistory.allChildren": "すべての子ども",
    "parentHistory.loading": "家族の学習履歴を読み込んでいます…",
    "parentHistory.missing": "履歴を確認する家族を選んでください。",
    "parentHistory.error": "家族の学習履歴を読み込めませんでした。",
    "parentHistory.empty": "家族の学習履歴はまだありません。",
    "parentHistory.points": "{awarded} / {available} 点",
    "parentHistory.withdraw": "課題を取り消す",
    "parentHistory.stop": "課題を終了する",
    "parentHistory.status.withdrawn": "取り消し済み",
    "parentHistory.status.stopped": "終了済み",
    "parentHistory.actionError": "課題の状態を更新できませんでした。もう一度お試しください。",
    "completedPaper.eyebrow": "解答済みのプリントを受け取りました",
    "completedPaper.mode": "解答済みのプリントを採点",
    "completedPaper.readingTitle": "プリントを読み込んでいます",
    "completedPaper.reviewTitle": "確認用の下書きを準備しています",
    "completedPaper.description":
      "元のプリントは非公開です。学習記録になる前に、問題の区切りと採点方法を確認してください。",
    "completedPaper.analysisProcessing": "解析中",
    "completedPaper.analysisReady": "解析結果を確認できます",
    "completedPaper.submitted": "採点に提出しました",
    "completedPaper.preparing": "プリントを準備しています",
    "completedPaper.notAssigned": "プリントは安全に保存され、まだ割り当てられていません",
    "completedPaper.submittedDetails":
      "このプリントは変更できない学習記録になりました。採点が終わると結果が表示されます。",
    "completedPaper.preparingDetails":
      "非公開の確認用下書きを準備しています。この画面は自動で更新され、まだ子どもの課題は作成されません。",
    "completedPaper.reviewDetails":
      "確認済みの問題と解答エリアを確定してください。その後で提出済みの解答を作成し、採点を始めます。",
    "completedPaper.openResults": "採点結果を開く",
    "completedPaper.prepareLocal": "ローカル AI 用の確認 JSON を準備",
    "completedPaper.localDetails":
      "元のページをローカル AI に添付し、このプロンプトをコピーして JSON だけの回答を保存してください。プロンプトは保存先パスを求めず、このアプリが非公開のプリント参照を追加します。",
    "completedPaper.serverDraft":
      "非公開 AI の下書きができました。確認前に、すべての問題と解答エリアを確認してください。",
    "completedPaper.promptCopied": "プロンプトをコピーしました",
    "completedPaper.copyPrompt": "ローカル AI プロンプトをコピー",
    "completedPaper.reviewJson": "確認済みプリントの JSON",
    "completedPaper.chooseJson": "確認済みプリント JSON を選択",
    "completedPaper.jsonHelp":
      "学習記録を作成する前に、問題の順序と解答エリアを検証します。",
    "completedPaper.reviewReady": "確認の準備完了 · 問題: {questions} · 解答エリア: {regions}",
    "completedPaper.previewQuestions": "確認済みの問題をプレビュー",
    "completedPaper.questionWording": "問題文",
    "completedPaper.questionWordingFor": "問題 {position} の問題文",
    "completedPaper.removeQuestion": "問題 {position} を削除",
    "completedPaper.addHandwritingQuestion": "手書き問題を追加",
    "completedPaper.referenceAnswer": "参照解答（非公開）",
    "completedPaper.referenceAnswerFor": "問題 {position} の参照解答",
    "completedPaper.acceptedAnswer": "正答",
    "completedPaper.acceptedAnswerFor": "問題 {position} の正答",
    "completedPaper.correctChoice": "正しい選択肢",
    "completedPaper.correctChoiceFor": "問題 {position} の正しい選択肢",
    "completedPaper.correctChoices": "正しい選択肢",
    "completedPaper.correctChoiceOptionFor": "問題 {position} の正しい選択肢 {choice}",
    "completedPaper.correctWordOrder": "正しい語順（1行に1語）",
    "completedPaper.correctWordOrderFor": "問題 {position} の正しい語順",
    "completedPaper.answerPages": "解答ページ番号",
    "completedPaper.answerPagesFor": "問題 {position} の解答ページ番号",
    "completedPaper.answerTranscription": "解答の文字起こし（非公開）",
    "completedPaper.answerTranscriptionFor": "問題 {position} の解答の文字起こし",
    "completedPaper.legibility": "手書きの判読性",
    "completedPaper.legibilityFor": "問題 {position} の手書きの判読性",
    "completedPaper.legibility.clear": "明瞭",
    "completedPaper.legibility.uncertain": "判読が不確か",
    "completedPaper.legibility.unreadable": "判読できない",
    "completedPaper.useWholePage": "ページ全体を解答範囲にする",
    "completedPaper.page": "{pages} ページ",
    "completedPaper.confirm": "確認して採点を始める",
    "completedPaper.confirming": "確認中…",
    "completedPaper.preparingReview": "非公開の確認を準備中",
    "completedPaper.error":
      "確認用 JSON は、確定するすべての問題と解答エリアに対応する必要があります。割り当ては行われていません。修正してもう一度お試しください。",
    "completedPaper.composeTitle": "子どもが解き終えたプリントをアップロード",
    "completedPaper.composeDescription":
      "元のスキャンまたは写真をアップロードします。手書きは非公開のまま、下書きを確認した後だけレビューされます。",
    "completedPaper.scans": "解答済みプリントのスキャン",
    "completedPaper.documentLanguage": "プリントの言語",
    "completedPaper.documentLanguageHelp":
      "子どもの画面言語ではなく、プリントに印刷された言語を選んでください。",
    "completedPaper.answerKey": "解答・採点基準（非公開・任意）",
    "completedPaper.chooseAnswerKey": "解答・採点基準を選択",
    "completedPaper.answerKeyHelp":
      "保護者と採点サービスのみが使います。子どもには表示されません。",
    "completedPaper.referenceMaterial": "元教材・例題（非公開・任意）",
    "completedPaper.chooseReferenceMaterial": "元教材・例題を追加",
    "completedPaper.referenceMaterialHelp":
      "学習目標の特定とプリントの解釈にのみ、非公開で使用します。",
    "completedPaper.choosePages": "解答済みプリントのページを選択",
    "completedPaper.pagesHelp":
      "撮影した順番で複数ページをアップロードできます。確認用下書きを確定するまで、課題の割り当てや採点は行われません。",
    "childExit.eyebrow": "保護者の確認",
    "childExit.title": "保護者管理 PIN を入力",
    "childExit.help":
      "この共用端末では、保護者が解除するまでお子さまの回答画面を開いたままにします。",
    "childExit.digitsEntered": "6桁中 {count} 桁を入力済み",
    "childExit.deleteDigit": "最後の数字を削除",
    "childExit.checking": "確認中…",
    "childExit.returnParent": "保護者モードに戻る",
    "childExit.error":
      "ログイン済みの保護者と正しい管理 PIN が必要です。",
    "family.parents": "保護者",
    "family.inviteParent": "別の保護者を招待",
    "family.inviteNote":
      "一つの家族には最大4人の保護者が参加できます。招待は7日後に期限切れになります。MVP では外部メールを送信しません。",
    "family.parentEmail": "保護者のメールアドレス",
    "family.createInvite": "招待を作成",
    "family.inviteCreated":
      "{email} の招待を作成しました。認証済みのメールアドレスでログインすると参加できます。",
    "family.saveError":
      "変更を保存できませんでした。入力内容を確認して、もう一度お試しください。",
    "family.accountSettings": "ログインと言語設定を開く",
  },
  zh: {
    "brand.tagline": "家庭学习",
    "nav.home": "首页",
    "nav.create": "创建",
    "nav.history": "历史",
    "nav.library": "题库",
    "nav.family": "家庭",
    "nav.work": "答题",
    "nav.review": "复习",
    "navigation.parent": "家长导航",
    "navigation.child": "孩子导航",
    "navigation.mobile": "{role}移动端导航",
    "identity.parent": "家长",
    "role.parent": "家长模式",
    "role.child": "孩子模式",
    "action.exitChild": "退出孩子模式",
    "language.label": "语言",
    "parentDashboard.eyebrow": "家长空间",
    "parentDashboard.title": "设置家庭学习空间",
    "parentDashboard.description":
      "先添加家庭和孩子，再为他们创建第一份练习。",
    "parentDashboard.firstStep": "第一步",
    "parentDashboard.familyAction": "创建或加入家庭",
    "parentDashboard.familyDetails":
      "家庭设置会分别保存每个孩子的任务、照片、结果和复习计划。",
    "parentDashboard.openFamilySetup": "进入家庭设置",
    "parentDashboard.private": "默认仅家庭可见",
    "parentDashboard.accountReady": "您的账号已准备好",
    "parentDashboard.accountReadyDetails":
      "示例家庭的数据不会关联到您的账号。家庭学习空间从空白开始，只显示您添加或加入的成员。",
    "parentDashboard.continueFamilySetup": "继续设置家庭",
    "parentDashboard.activeFamilyDescription": "这个家庭有 {count} 个孩子准备开始学习。",
    "parentDashboard.learningToday": "今日学习",
    "parentDashboard.noChildren": "请先添加孩子，再创建第一份练习。",
    "parentDashboard.quickActions": "家庭快捷操作",
    "parentDashboard.workspaceUnavailable": "无法加载您的家庭学习空间",
    "parentDashboard.workspaceUnavailableDetails":
      "您的账号仍保持登录。请重新加载家庭数据。",
    "parentDashboard.tryAgain": "重试",
    "family.eyebrow": "家庭学习空间",
    "family.createTitle": "创建您的家庭",
    "family.loadingTitle": "正在加载家庭空间…",
    "family.description":
      "家长共用一个家庭空间，每位成员都可以独立选择界面语言。",
    "family.switcherLabel": "切换家庭",
    "family.currentLabel": "当前家庭",
    "family.choose": "选择家庭",
    "family.newNameLabel": "新家庭名称",
    "family.newNamePlaceholder": "新家庭名称",
    "family.add": "添加家庭",
    "family.invitation": "发送给 {email} 的家庭邀请将于 {date} 失效。",
    "family.accept": "接受邀请",
    "family.children": "孩子",
    "family.profilesPin": "孩子档案与 PIN",
    "family.managementPin": "家长管理 PIN",
    "family.sixDigits": "6 位数字",
    "family.managementUnlocked": "管理权限已解锁 10 分钟",
    "family.unlockPin": "解锁 PIN 管理",
    "family.setManagementPin": "设置管理 PIN",
    "family.managementNote":
      "修改孩子的 PIN 前，需要先进行一次短时管理解锁。",
    "family.uiLanguage": "{language} 界面",
    "family.languageFor": "{name} 的界面语言",
    "family.createPractice": "创建练习",
    "family.childSignIn": "孩子登录",
    "family.newPinFor": "为 {name} 设置新 PIN",
    "family.pinPlaceholder": "6 位 PIN",
    "family.savePin": "保存 PIN",
    "family.managePin": "管理 PIN",
    "family.childName": "孩子姓名",
    "family.grade": "年级",
    "family.sixDigitPin": "六位 PIN",
    "family.childUiLanguage": "孩子界面语言",
    "family.addChild": "添加孩子",
    "language.option.zh": "中文",
    "language.option.ja": "日文",
    "language.option.en": "英文",
    "childLogin.eyebrow": "孩子登录",
    "childLogin.title": "输入六位 PIN",
    "childLogin.help": "家长可以在家庭设置中重置这个 PIN。",
    "childLogin.digitsEntered": "已输入 {count}/6 位数字",
    "childLogin.deleteDigit": "删除最后一位数字",
    "childLogin.opening": "正在打开…",
    "childLogin.openWork": "打开我的练习",
    "childLogin.error": "PIN 不正确，请重试。",
    "childLogin.expired": "孩子会话已过期，请重新输入 PIN 后继续。",
    "childLogin.returnParent": "返回家长模式",
    "childHome.today": "今天",
    "childHome.title": "准备好取得一个小进步了吗？",
    "childHome.assignmentOne": "{count} 份练习",
    "childHome.assignmentMany": "{count} 份练习",
    "childHome.reviewOne": "{count} 道复习题",
    "childHome.reviewMany": "{count} 道复习题",
    "childHome.summary": "{assignments}，{reviews}。",
    "childHome.loadingSummary": "正在读取今天的学习安排…",
    "childHome.start": "开始",
    "childHome.status.inProgress": "进行中",
    "childHome.status.submitted": "已提交",
    "childHome.status.grading": "批改中",
    "childHome.status.resultsReady": "结果已就绪",
    "childHome.status.completed": "已完成",
    "childHome.examMode": "考试模式",
    "childHome.practiceMode": "练习模式",
    "childHome.questions": "{count} 道题",
    "childHome.minutes": "{count} 分钟",
    "childHome.noTimer": "不限时",
    "childHome.viewStatus": "查看状态",
    "childHome.openWork": "打开练习",
    "childHome.allClear": "全部完成",
    "childHome.noAssigned": "目前没有待完成的练习。",
    "childHome.parentCanAssign": "家长可以从家庭学习空间安排下一份练习。",
    "childHome.todayReview": "今日复习",
    "childHome.shortQuestions": "{count} 道短题",
    "childHome.reviewNote":
      "今天可以跳过。未完成的复习会自动平缓顺延。",
    "childHome.startReview": "开始复习",
    "childHome.viewReview": "查看复习",
    "childHome.localDemo":
      "孩子使用真实档案登录前，暂时显示本机示例。",
    "worksheet.assignedPractice": "已安排的练习",
    "worksheet.multipleChoice": "请选择所有正确答案",
    "worksheet.buildSentence": "组合句子",
    "worksheet.chooseWords": "请从下方选择单词…",
    "worksheet.reset": "重置",
    "worksheet.playSlow": "以 0.85 倍速播放",
    "worksheet.playsUsed": "已播放 {count}/{limit} 次",
    "worksheet.singleChoice": "请选择一个答案",
    "worksheet.photoInput": "拍照或选择图片",
    "worksheet.addMoreImages": "继续添加答案图片",
    "worksheet.photoHelp": "请逐题上传。图片会按照拍摄顺序保存。",
    "worksheet.uploadedImages": "已上传的答案图片",
    "worksheet.yourAnswer": "你的答案",
    "worksheet.typeHere": "在这里输入…",
    "worksheet.handwritingAlternative":
      "也可以从菜单将这道题切换为手写作答。",
    "worksheet.questionMeta": "第 {number} 题 · {points}",
    "worksheet.pointOne": "{count} 分",
    "worksheet.pointMany": "{count} 分",
    "worksheet.todayPractice": "今日练习",
    "worksheet.practiceMode": "练习模式",
    "worksheet.saving": "正在保存…",
    "worksheet.saved": "已保存",
    "worksheet.savedDevice": "已保存在此设备",
    "worksheet.autoSave": "自动保存",
    "worksheet.layout": "题目显示方式",
    "worksheet.focusMode": "逐题模式",
    "worksheet.sheetMode": "整份模式",
    "worksheet.answered": "已作答",
    "worksheet.goToQuestion": "前往第 {number} 题",
    "worksheet.examTimer": "考试倒计时 · 归零后自动提交",
    "worksheet.noTimer": "不限时 · 请从容作答",
    "worksheet.previous": "上一题",
    "worksheet.next": "下一题",
    "worksheet.submit": "提交全部答案",
    "worksheet.submitQuestion": "只提交这一题批改",
    "worksheet.submitQuestionAgain": "重新提交审阅",
    "worksheet.questionSubmitted": "这一题已经提交",
    "worksheet.regradeAnswer": "保留答案并重新评判",
    "worksheet.regradingAnswer": "正在重新评判这一答案…",
    "worksheet.redoQuestion": "清空并重做这一题",
    "worksheet.preparingRedo": "正在准备空白答案…",
    "worksheet.confirmQuestionTitle": "只提交这一题吗？",
    "worksheet.confirmQuestionBody":
      "只提交第 {number} 题。其他题仍可继续作答，但这一题提交后不能再修改。",
    "worksheet.confirmQuestionAction": "确认只提交这一题",
    "worksheet.confirmAllTitle": "提交整份练习吗？",
    "worksheet.confirmAllBody":
      "还有 {count} 题未作答，这些题会按错误处理。整份提交后，所有答案都不能再修改。",
    "worksheet.confirmAllAction": "确认提交整份",
    "worksheet.cancel": "取消",
    "worksheet.grading": "正在批改这一题…",
    "worksheet.result.correct": "回答正确。",
    "worksheet.result.incorrect": "请订正这一题。",
    "worksheet.result.uncertain": "自动批改暂时无法确定。",
    "worksheet.result.needsParentReview": "等待家长确认。",
    "worksheet.result.pending": "正在等待结果。",
    "worksheet.result.action.correct": "可以继续下一题。",
    "worksheet.result.action.incorrect": "请查看反馈并重新完成这一题。",
    "worksheet.result.action.review": "请让家长确认这份答案。",
    "worksheet.loading": "正在加载",
    "worksheet.loadingTitle": "正在打开已安排的练习…",
    "worksheet.loadingBody": "练习马上就会显示。",
    "worksheet.unavailable": "暂时无法使用",
    "worksheet.signInRequired": "请先以孩子身份登录，再打开练习。",
    "worksheet.loadError": "无法打开这份练习。",
    "worksheet.tryAgain": "请返回首页，再重新打开练习。",
    "handwriting.tools": "手写工具",
    "handwriting.thinPen": "细笔",
    "handwriting.thickPen": "粗笔",
    "handwriting.eraser": "橡皮擦",
    "handwriting.undo": "撤销",
    "handwriting.redo": "重做",
    "handwriting.clear": "清除手写内容",
    "handwriting.clearConfirm": "确定清除全部手写内容吗？",
    "handwriting.keep": "保留手写内容",
    "handwriting.clearNow": "立即清除",
    "handwriting.expandRight": "向右增加书写空间",
    "handwriting.expandDown": "向下增加书写空间",
    "handwriting.area": "手写作答区域",
    "handwriting.help":
      "请用手指或触控笔书写，需要时可向右或向下增加空间，内容会持续保存。",
    "submitted.eyebrow": "已全部提交",
    "submitted.title": "系统正在批改你的答案",
    "submitted.description":
      "你已经完成整份练习。所有题目批改完成后，结果会一次显示。",
    "submitted.duration": "通常只需几分钟",
    "submitted.viewResults": "查看结果",
    "submitted.preparing": "正在准备结果…",
    "results.preparingCorrections": "正在准备订正…",
    "results.correctAnswers": "订正这些题",
    "results.ready": "结果已就绪",
    "results.checking": "正在批改",
    "results.goodWork": "做得好，{name}",
    "results.almostReady": "马上就好",
    "results.unavailable": "暂时无法显示结果",
    "results.unavailableTitle": "没有可显示的结果",
    "results.unavailableBody": "请从学习记录中打开已提交练习的结果。",
    "results.correctionOne": "有 {count} 道题需要再试一次或等待家长确认。",
    "results.correctionMany": "有 {count} 道题需要再试一次或等待家长确认。",
    "results.fullResult": "所有题目批改完成后才会显示完整结果。",
    "results.points": "分",
    "results.question": "第 {number} 题",
    "results.correct": "正确",
    "results.tryAgain": "再试一次",
    "results.parentCheck": "等待家长确认",
    "results.demoAction": "检查主语和动词词尾。",
    "results.openError": "无法打开订正，请重试。",
    "parentResults.eyebrow": "{name} · {title}",
    "parentResults.title": "确认作答结果",
    "parentResults.description":
      "这里只显示手写、照片和需要家长判断的答案。",
    "parentResults.loading": "正在加载答案…",
    "parentResults.error": "无法加载结果，请返回学习记录后重试。",
    "parentResults.missingAttempt": "请从学习记录中的已完成练习打开本页。",
    "parentResults.processing": "评卷结果正在整理，页面会自动更新。",
    "parentResults.allReviewed": "所有需要确认的答案都已处理。",
    "parentResults.question": "第 {number} 题 · {type}",
    "parentResults.handwriting": "手写",
    "parentResults.photo": "照片作答",
    "parentResults.answer": "孩子的答案",
    "parentResults.handwritingPreview": "孩子的手写答案",
    "parentResults.photoList": "已上传的答案照片",
    "parentResults.parentNeeded":
      "系统没有自动判断这份图像答案，请家长根据孩子的作答来裁定。",
    "parentResults.markCorrect": "判为正确",
    "parentResults.markIncorrect": "需要订正",
    "parentResults.saving": "正在保存…",
    "parentResults.savedCorrect": "这道题已由家长判为正确。",
    "parentResults.savedIncorrect": "这道题已由家长判为错误。",
    "parentResults.decisionError": "无法保存裁定，请重试。",
    "parentResults.wholeSet": "整份练习",
    "parentResults.score": "{awarded} / {available} 分",
    "parentResults.correct": "正确",
    "parentResults.correction": "待订正",
    "parentResults.pending": "家长确认",
    "parentResults.releaseNote":
      "自动判题结果和家长裁定会共同组成最终成绩。",
    "review.today": "今日复习",
    "review.quickOne": "{count} 道快速复习题",
    "review.quickMany": "{count} 道快速复习题",
    "review.description": "根据当前水平安排的短时复习，不限时间。",
    "review.loading": "正在加载今日复习…",
    "review.none": "今天没有到期的复习。",
    "review.backHome": "返回首页",
    "review.level.reinforcement": "巩固",
    "review.level.standard": "标准",
    "review.level.challenge": "挑战",
    "review.next": "下次复习：{date}",
    "review.gotIt": "我会了",
    "review.anotherTry": "我需要再练一次",
    "review.skip": "今天跳过",
    "history.eyebrow": "你的练习",
    "history.title": "学习记录",
    "history.description": "已完成的练习、分数和订正记录。",
    "history.loading": "正在加载学习记录…",
    "history.empty": "目前还没有学习记录。",
    "history.error": "无法加载学习记录，请重新登录。",
    "history.assigned": "已安排",
    "history.correctionOne": "{count} 道待订正",
    "history.correctionMany": "{count} 道待订正",
    "history.status.draft": "草稿",
    "history.status.confirmed": "已确认",
    "history.status.assigned": "已安排",
    "history.status.inProgress": "进行中",
    "history.status.submitted": "已提交",
    "history.status.grading": "批改中",
    "history.status.resultsReady": "结果已就绪",
    "history.status.correcting": "订正中",
    "history.status.completed": "已完成",
    "history.status.other": "已更新",
    "history.openResults": "打开 {title} 的结果",
    "history.results": "结果",
    "parentHistory.eyebrow": "家庭学习记录",
    "parentHistory.title": "学习记录",
    "parentHistory.description": "已完成、批改中和已归档的家庭练习。",
    "parentHistory.filters": "学习记录筛选",
    "parentHistory.allChildren": "所有孩子",
    "parentHistory.loading": "正在加载家庭学习记录…",
    "parentHistory.missing": "请选择一个家庭查看学习记录。",
    "parentHistory.error": "无法加载家庭学习记录。",
    "parentHistory.empty": "目前还没有家庭学习记录。",
    "parentHistory.points": "{awarded} / {available} 分",
    "parentHistory.withdraw": "撤回练习",
    "parentHistory.stop": "结束练习",
    "parentHistory.status.withdrawn": "已撤回",
    "parentHistory.status.stopped": "已结束",
    "parentHistory.actionError": "无法更新练习状态，请重试。",
    "completedPaper.eyebrow": "已收到已完成的试卷",
    "completedPaper.mode": "批改已完成的试卷",
    "completedPaper.readingTitle": "正在读取试卷",
    "completedPaper.reviewTitle": "正在准备审核草稿",
    "completedPaper.description":
      "原始试卷保持私密。必须确认题目边界与评分方式，才会成为学习记录。",
    "completedPaper.analysisProcessing": "正在解析",
    "completedPaper.analysisReady": "解析已可审核",
    "completedPaper.submitted": "已提交批改",
    "completedPaper.preparing": "正在准备你的试卷",
    "completedPaper.notAssigned": "试卷已安全保存，尚未安排给孩子",
    "completedPaper.submittedDetails":
      "这份试卷现在是不可修改的学习记录。批改完成后会显示结果。",
    "completedPaper.preparingDetails":
      "正在准备私密审核草稿。页面会自动更新，尚未创建任何孩子任务。",
    "completedPaper.reviewDetails":
      "请确认审核后的题目和答题区域。确认后才会创建已提交的作答并开始批改。",
    "completedPaper.openResults": "打开批改结果",
    "completedPaper.prepareLocal": "准备本地 AI 审核 JSON",
    "completedPaper.localDetails":
      "将原始页面附给本地 AI，复制此提示词，并保存它只含 JSON 的回答。提示词不会要求存储路径；应用会自行添加私密试卷引用。",
    "completedPaper.serverDraft":
      "私密 AI 草稿已生成。确认前请逐题核对题目和答题区域。",
    "completedPaper.promptCopied": "提示词已复制",
    "completedPaper.copyPrompt": "复制本地 AI 提示词",
    "completedPaper.reviewJson": "已审核试卷 JSON",
    "completedPaper.chooseJson": "选择已审核试卷 JSON",
    "completedPaper.jsonHelp":
      "应用会在创建学习记录前验证题目顺序和答题区域。",
    "completedPaper.reviewReady": "审核准备就绪 · 题目：{questions} · 答题区域：{regions}",
    "completedPaper.previewQuestions": "预览已确认题目",
    "completedPaper.questionWording": "题目文字",
    "completedPaper.questionWordingFor": "第 {position} 题题目文字",
    "completedPaper.removeQuestion": "删除第 {position} 题",
    "completedPaper.addHandwritingQuestion": "添加手写题",
    "completedPaper.referenceAnswer": "参考答案（私密）",
    "completedPaper.referenceAnswerFor": "第 {position} 题参考答案",
    "completedPaper.acceptedAnswer": "正确答案",
    "completedPaper.acceptedAnswerFor": "第 {position} 题正确答案",
    "completedPaper.correctChoice": "正确选项",
    "completedPaper.correctChoiceFor": "第 {position} 题正确选项",
    "completedPaper.correctChoices": "正确选项",
    "completedPaper.correctChoiceOptionFor": "第 {position} 题正确选项 {choice}",
    "completedPaper.correctWordOrder": "正确词序（每行一个词元）",
    "completedPaper.correctWordOrderFor": "第 {position} 题正确词序",
    "completedPaper.answerPages": "答题页码",
    "completedPaper.answerPagesFor": "第 {position} 题答题页码",
    "completedPaper.answerTranscription": "作答文字识别（私密）",
    "completedPaper.answerTranscriptionFor": "第 {position} 题作答文字识别",
    "completedPaper.legibility": "手写清晰度",
    "completedPaper.legibilityFor": "第 {position} 题手写清晰度",
    "completedPaper.legibility.clear": "清晰",
    "completedPaper.legibility.uncertain": "不确定",
    "completedPaper.legibility.unreadable": "无法辨认",
    "completedPaper.useWholePage": "改用整页作为答题范围",
    "completedPaper.page": "第 {pages} 页",
    "completedPaper.confirm": "确认并开始批改",
    "completedPaper.confirming": "正在确认…",
    "completedPaper.preparingReview": "正在准备私密审核",
    "completedPaper.error":
      "审核 JSON 必须匹配每一道已确认题目和答题区域。尚未安排任何练习；请修正后重试。",
    "completedPaper.composeTitle": "上传孩子已经做完的试卷",
    "completedPaper.composeDescription":
      "上传原始扫描件或照片。手写内容保持私密，只会在你确认草稿后审核。",
    "completedPaper.scans": "已完成试卷扫描件",
    "completedPaper.documentLanguage": "试卷语言",
    "completedPaper.documentLanguageHelp":
      "请选择试卷印刷内容的语言，而不是孩子的界面语言。",
    "completedPaper.answerKey": "答案与评分标准（私密，可选）",
    "completedPaper.chooseAnswerKey": "选择答案或评分标准",
    "completedPaper.answerKeyHelp":
      "仅家长和批改服务可用，孩子端永远不会看到。",
    "completedPaper.referenceMaterial": "原教材或例题（私密，可选）",
    "completedPaper.chooseReferenceMaterial": "添加原教材或例题",
    "completedPaper.referenceMaterialHelp":
      "仅用于识别学习目标和理解试卷内容，不会向孩子展示。",
    "completedPaper.choosePages": "选择已完成试卷页面",
    "completedPaper.pagesHelp":
      "可按拍摄顺序上传多页。在确认审核草稿前，不会安排练习或开始批改。",
    "childExit.eyebrow": "家长确认",
    "childExit.title": "输入家长管理 PIN",
    "childExit.help":
      "在家长解锁这台共用设备前，孩子的作答画面会保持打开。",
    "childExit.digitsEntered": "已输入 {count}/6 位数字",
    "childExit.deleteDigit": "删除最后一位数字",
    "childExit.checking": "正在确认…",
    "childExit.returnParent": "返回家长模式",
    "childExit.error": "需要已登录的家长和正确的管理 PIN。",
    "family.parents": "家长",
    "family.inviteParent": "邀请另一位家长",
    "family.inviteNote":
      "一个家庭最多可有四位家长。邀请将在 7 天后失效。MVP 暂不发送外部邮件。",
    "family.parentEmail": "家长邮箱",
    "family.createInvite": "创建邀请",
    "family.inviteCreated":
      "已为 {email} 创建邀请。对方使用这个已验证邮箱登录后即可接受邀请。",
    "family.saveError": "无法保存更改。请检查填写内容后重试。",
    "family.accountSettings": "打开我的登录与语言设置",
  },
} as const;

type MessageKey = keyof (typeof messages)["en"];
type MessageValues = Record<string, string | number>;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: MessageKey, values?: MessageValues) => string;
};

function interpolate(message: string, values?: MessageValues) {
  if (!values) {
    return message;
  }

  return message.replace(/\{(\w+)\}/g, (match, key: string) =>
    Object.hasOwn(values, key) ? String(values[key]) : match,
  );
}

const defaultLanguageContext: LanguageContextValue = {
  language: "en",
  setLanguage: () => undefined,
  t: (key, values) => interpolate(messages.en[key], values),
};

const LanguageContext = createContext<LanguageContextValue>(
  defaultLanguageContext,
);

const languageEvent = "luma-language-change";

function readLanguage(storageKey: string): Language {
  const stored = window.localStorage.getItem(`luma-language:${storageKey}`);
  return stored === "ja" || stored === "zh" ? stored : "en";
}

function subscribeToLanguage(onChange: () => void) {
  window.addEventListener("storage", onChange);
  window.addEventListener(languageEvent, onChange);
  return () => {
    window.removeEventListener("storage", onChange);
    window.removeEventListener(languageEvent, onChange);
  };
}

export function LanguageProvider({
  children,
  storageKey = "public",
}: {
  children: ReactNode;
  storageKey?: string;
}) {
  const language = useSyncExternalStore<Language>(
    subscribeToLanguage,
    () => readLanguage(storageKey),
    () => "en",
  );

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage: (nextLanguage) => {
        window.localStorage.setItem(
          `luma-language:${storageKey}`,
          nextLanguage,
        );
        document.documentElement.lang = nextLanguage;
        window.dispatchEvent(new Event(languageEvent));
      },
      t: (key, values) => interpolate(messages[language][key], values),
    }),
    [language, storageKey],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
